# .github/workflows/train.yml
name: Train pipeline

on:
  push:
    branches: [ "main", "lesson-10" ]

jobs:
  train:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Start Step Function
        run: |
          aws stepfunctions start-execution \
            --state-machine-arn ${{ secrets.STEP_FUNCTION_ARN }} \
            --name train-${{ github.run_id }} \
            --input '{"source":"github","commit":"${{ github.sha }}"}'
